name: Example Workflow

on: [push]

jobs:
  runHelloWorld:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Run the hello world action
        uses: theswarnim/hello-world-docker-action@v3
